#! /usr/bin/env bash

apt-get update > /dev/null
apt-get install --yes --force-yes curl
curl -L https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm install ruby
rvm rubygems current
gem install rails
apt-get install --yes --force-yes libxml2